version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - local_network

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - local_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: spaceship_test_user
      MONGO_INITDB_ROOT_PASSWORD: spaceship_test_pass
    volumes:
      - mongo_data:/data/db

networks:
  local_network:
    driver: bridge

volumes:
  mongo_data: